build:
  version: "3.1"

loans:
  message: "Welcome to EazyBank loans related productiorr APIs "
  contactDetails:
    name: "Prod Grega - Product Owner"
    email: "prod@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934
